services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - zip

zip:
  stage: zip
  script:
    - echo "Zipping utils..."
    - zip -r modules/utils.zip utils/
    - echo "Utils zipped."
  artifacts:
    paths:
      - modules/utils.zip