stages:
  - test_ssh
  - zip

test_ssh:
  stage: test_ssh
  script:
    - ssh -T git@gitlab.com

zip:
  stage: zip
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa.pub
  script:
    - echo "Zipping utils..."
    - zip -r modules/utils.zip utils/
    - echo "Utils zipped."
  artifacts:
    paths:
      - modules/utils.zip