image: alpine:latest  # Use the Docker image for the main job

services:
  - docker:dind  # Use Docker-in-Docker service

variables:
  DOCKER_HOST: tcp://docker:2375/  # Set Docker host to connect to the dind service
  DOCKER_DRIVER: overlay2  # Use the overlay2 storage driver

stages:
  - zip

zip:
  stage: zip
  before_script:
    - apk add --no-cache zip bash
  script:
    - echo "Current directory contents:"
    - ls -la
    - echo "Zipping utils..."
    - zip -r modules/utils.zip utils/  # Zip the utils directory
    - echo "Utils zipped."
  artifacts:
    paths:
      - modules/utils.zip